export const TMDB_CONFIG_LANGUAGES = 'TMDB_CONFIG_LANGUAGES';
export const TMDB_CHANGE_LANGUAGE = 'TMDB_CHANGE_LANGUAGE';

export const TMDB_GET_ALL_MOVIES = 'TMDB_GET_ALL/MOVIES';
export const TMDB_GET_ALL_TV = 'TMDB_GET_ALL/MOVIES';
export const TMDB_GET_ALL_PEOPLE = 'TMDB_GET_ALL/MOVIES';

export const TMDB_GET_MOVIE_POPULARS = 'TMDB_GET_MOVIE_POPULARS';
export const TMDB_GET_MOVIE_UPCOMING = 'TMDB_GET_MOVIE_UPCOMING';
export const TMDB_GET_MOVIE_TOP_RATED = 'TMDB_GET_MOVIE_TOP_RATED';
export const TMDB_GET_MOVIE_NOW_PLAYING = 'TMDB_GET_MOVIE_NOW_PLAYING';
export const TMDB_GET_MOVIE_TREND = 'TMDB_GET_MOVIE_TREND';

export const TMDB_GET_DETAIL_MOVIE = 'TMDB_GET_DETAIL_MOVIE';

export const TMDB_GET_MOVIE_SIMILAR = 'TMDB_GET_MOVIE_SIMILAR';
export const TMDB_GET_MOVIE_REVIEWS = 'TMDB_GET_MOVIE_REVIEWS';
export const TMDB_GET_MOVIE_LISTS = 'TMDB_GET_MOVIE_LISTS';
export const TMDB_GET_MOVIE_KEYWORDS = 'TMDB_GET_MOVIE_KEYWORDS';
export const TMDB_GET_MOVIE_IMAGES = 'TMDB_GET_MOVIE_IMAGES';
export const TMDB_GET_MOVIE_RECOMMENDATIONS = 'TMDB_GET_MOVIE_RECOMMENDATIONS';
